kind: Deployment
apiVersion: apps/v1
metadata:
  name: dep
spec:
  selector:
    matchLabels:
      name: pradeep
  replicas: 4
  template:
    metadata:
      name: pod
      labels:
        name: pradeep
    spec:
      containers:
      - name: nod
        image: pradeepcoeb/tomcat:23
        imagePullSecrets:
          - name: dockerhub-credentials 
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: '100m'
          limits:
            cpu: '100m'
